[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
hexagon_404 = "6BAVaAjXJmFWsYoWe2WRRTjGsvrt6U9PPMB6SBnb1V4H"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "localhost:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899
slots_per_epoch = "64"
